name: Deploy to EC2 via SSH

on:
  push:
    branches:
      - main  # Adjust based on your main branch name

jobs:
  deploy:
    name: Deploy Docker Image to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull ${{ secrets.ECR_IMAGE_URI }}
            docker stop mltest || true
            docker rm mltest || true
            docker run -d -p 8080:8080 --name mltest ${{ secrets.ECR_IMAGE_URI }}
